### ISSUE TITLE
add `pkg-config` file

### ISSUE THREAD

**Issue by eugenwintersberger** [nexusformat/code#384]
For Linux systems we should definitely add a `pkg-config` file to make code building easier.

**Comment by eugenwintersberger** [comment]
Want to provide a pkg-config file for each binding (currently there is only one for the C and the C++ code). Thus we would have

* `nexus.pc` -- for the C-API
* `nexus-cpp.pc` -- for the C++-API
* `nexus-f77.pc` -- for Fortran77

As I have currently no glue where to install the `.mod` files for Fortran 90 I cannot write a pkg-config file for this binding. This situation still needs to be solved.

**Comment by rayosborn** [comment]
It's a long time since I programmed in F90, although I think I wrote most of the original NeXus bindings. I did a quick search of online discussions of this topic, and could find no satisfactory conclusion, but the simplest option would seem to me to be to put it in the same location as the libraries themselves. Most compilers provide a switch pointing to the module subdirectory, so it doesn't really matter where they are as long as it is documented. You would need a naming convention if there were multiple versions, i.e., for 32-bit and 64-bit compilations.
