### ISSUE TITLE
Unresolved external symbol of HDF5 function

### ISSUE THREAD

**Issue by hanashima** [nexusformat/code#460]
I tried to build nexus using Visual Studio 2017, and got some Error LINK2019 (unsolved external symbol).

> > LNK2019: unresolved external symbol __imp_H5Oget_info referenced in function NX5getattrinfo  NeXus_Shared_Library	napi5.obj
LNK2019: unresolved external symbol __imp_H5Oget_info_by_name referenced in function group_info1  NeXus_Shared_Library	napi5.obj

I checked hdf5.lib(pre-build binary version for windows10, Visual Studio2017), because these symbols seem to be HDF5 functions.

> $ nm.exe hdf5.lib | grep H5Oget_info
0000000000000000 I __imp_H5Oget_info1
0000000000000000 T H5Oget_info1
0000000000000000 I __imp_H5Oget_info2
0000000000000000 T H5Oget_info2
0000000000000000 I __imp_H5Oget_info_by_idx1
0000000000000000 T H5Oget_info_by_idx1
0000000000000000 I __imp_H5Oget_info_by_idx2
0000000000000000 T H5Oget_info_by_idx2
0000000000000000 I __imp_H5Oget_info_by_name1
0000000000000000 T H5Oget_info_by_name1
0000000000000000 I __imp_H5Oget_info_by_name2
0000000000000000 T H5Oget_info_by_name2

After changing "H5Oget_info(_by_name)" to "H5Oget_info(_by_name)1" in napi5.c,  the build succeeded.
Will nexus format work now as intended?

**Comment by mkoennecke** [comment]
Yuki,


Am 10.01.2019 um 10:18 schrieb Yuki Hanashima <notifications@github.com<mailto:notifications@github.com>>:


I tried to build nexus using Visual Studio 2017, and got some Error LINK2019 (unsolved external symbol).

LNK2019: unresolved external symbol __imp_H5Oget_info referenced in function NX5getattrinfo NeXus_Shared_Library napi5.obj
LNK2019: unresolved external symbol __imp_H5Oget_info_by_name referenced in function group_info1 NeXus_Shared_Library napi5.obj

I checked hdf5.lib(pre-build binary version for windows10, Visual Studio2017), because these symbols seem to be HDF5 functions.

$ nm.exe hdf5.lib | grep H5Oget_info
0000000000000000 I __imp_H5Oget_info1
0000000000000000 T H5Oget_info1
0000000000000000 I __imp_H5Oget_info2
0000000000000000 T H5Oget_info2
0000000000000000 I __imp_H5Oget_info_by_idx1
0000000000000000 T H5Oget_info_by_idx1
0000000000000000 I __imp_H5Oget_info_by_idx2
0000000000000000 T H5Oget_info_by_idx2
0000000000000000 I __imp_H5Oget_info_by_name1
0000000000000000 T H5Oget_info_by_name1
0000000000000000 I __imp_H5Oget_info_by_name2
0000000000000000 T H5Oget_info_by_name2

After changing "H5Oget_info(_by_name)" to "H5Oget_info(_by_name)1" in napi5.c, the build succeeded.
Will nexus format work now as intended?

Hmhh. There is information missing such as HDF library version etc. From what I see here: can you build the test which comes with NAPI? If you can do
that and it runs OK, then the likelihood that your build of the NAPI is good increases significantly. Also, normally HDF does a pretty good job maintaining
backwards compatibility through Macros. I suspect there is #define set inappropriately.

Regards,

     Mark Koennecke

**Comment by till314** [comment]
Mark's explanation seems correct. See

https://confluence.hdfgroup.org/display/HDF5/H5O_GET_INFO_BY_NAME

**Comment by hanashima** [comment]
Both comments were useful.
Thank you, all of you.
